#!/bin/bash
cat << EOF
Welcome to Docker service auto-updater!
Use docker compose ls to find services...

EOF

# Prompt for docker name
read -p "Enter the Docker Compose project name to check: " name

# Get the Docker Compose file path associated with the project
compose_file_path=$(docker-compose ls --filter "Name=$name" --format json | awk -F',' '{print $3}' | awk -F'"' '{print $4}')

# Check if a docker-compose.yml file was found
if [ -n "$compose_file_path" ]; then
    echo "Docker Compose project '$name' is associated with Docker Compose file: $compose_file_path"
else
    echo "Unable to find the Docker Compose file for Docker Compose project '$name'."
    exit
fi
# Run the script without any input
echo -e "\nDo you want to run with defaults"
select yn in "Yes" "No"
do 
  case $yn in 
    Yes ) break ;;
    No ) break ;;
  esac
done
if [[ $yn =~ "Yes" ]]
then 
  path_to_save="/home/$USER/scripts/docker_updates"
  if [ -e "$path_to_save" ]
  then
    echo -e "\nSaving to default path ($path_to_save)..."
  else 
    echo -e "\nCreating default path ($path_to_save)..."
    mkdir $path_to_save || echo "Can't create path" ; exit
  fi
  echo "Creating script... "
  echo -e "cd $compose_file_path\ndocker compose pull\ndocker compose up -d" > "$path_to_save"/"$name"_update.sh
  sch="0 0 * * 5"
  echo "Adding crontab task... "
  (crontab -l ; echo "$sch ~/scripts/docker_updates/"$name"_update.sh") | crontab -
  echo -e "\nDone!"
  exit
else 
  :
fi

# Create script that will run the update
echo -e "\nWhere do you want to save the script?"
select place in "default" "manual"
do 
  case $place in 
    default ) path_to_save="/home/$USER/scripts/docker_updates" ; break ;;
    manual ) read -p "Enter the path (use full path): " path_to_save ; break ;;
  esac
done

if [[ $place =~ "default" ]]
then 
  if [ -e "$path_to_save" ]
  then
    echo -e "\nSaving to default path ($path_to_save)..."
  else 
    echo -e "\nCreating default path ($path_to_save)..."
    mkdir $path_to_save || echo "Can't create path" ; exit
  fi
else
  if [ -e "$path_to_save" ]
  then
    echo -e "\nSaving to path..."
  else 
    echo -e "\nCreating path..."
    mkdir $path_to_save || echo "Can't create path" ; exit
  fi
fi
echo "Creating script..."
# if [ -d ~/scripts/docker_updates ]
# then 
#   echo "Path exists"
# else 
#   echo "Path doesn't exist. Creating..."
#   mkdir ~/scripts/docker_updates
#fi
echo -e "cd $compose_file_path\ndocker compose pull\ndocker compose up -d" > "$path_to_save"/"$name"_update.sh

echo "Script ready"

#Update automation
echo -e "\nDo you want to use crontab to automate the update?"
select yn in "Yes" "No"
do
  case $yn in
    Yes ) break;;
    No ) echo "Done!" ; exit;;
  esac
done 

#Update crontab
echo -e "\nHow often should crontab run the update?"
select timer in "daily" "weekly" "monthly" "manual"
do 
  case $timer in 
    daily ) sch="0 0 * * *"; break;;
    weekly ) sch="0 0 * * 5"; break;;
    monthly ) sch="0 0 1 * *"; break;;
    manual ) read -p "Enter cron expression. WARNING! Won't work if not using the correct format: " sch; break;;
  esac
done
echo -e "\nYou have selected $timer"
(crontab -l ; echo "$sch ~/scripts/docker_updates/"$name"_update.sh") | crontab -
sleep 1
echo -e "\nThis is your current crontab:"
crontab -l
echo -e "\nDone!"

